import { describe, expect, it } from "vitest";
import type { Request } from "../types.ts";
import {
    buildAutoGeneratedHeadersPreview,
    CALCULATED_HEADER_VALUE,
    NOT_SET_HEADER_VALUE,
} from "./requestHeadersPreview.ts";

function buildRequest(overrides: Partial<Request> = {}): Request {
    return {
        id: "req_1",
        name: "Request 1",
        method: "post",
        url: "https://api.example.com/v1/ping",
        headers: [],
        query: [],
        body: { type: "none" },
        auth: { type: "none" },
        extractors: [],
        scripts: { pre_request: "", post_response: "" },
        ...overrides,
    };
}

function rowValue(rows: ReturnType<typeof buildAutoGeneratedHeadersPreview>, key: string): string {
    const found = rows.find((row) => row.key === key);
    if (!found) {
        throw new Error(`Expected row '${key}'`);
    }
    return found.value;
}

describe("buildAutoGeneratedHeadersPreview", () => {
    it("derives host and reqwest defaults", () => {
        const rows = buildAutoGeneratedHeadersPreview({
            request: buildRequest(),
        });

        expect(rowValue(rows, "Host")).toBe("api.example.com");
        expect(rowValue(rows, "Accept")).toBe("*/*");
        expect(rowValue(rows, "User-Agent")).toBe(NOT_SET_HEADER_VALUE);
    });

    it("uses user-defined headers as effective preview values", () => {
        const rows = buildAutoGeneratedHeadersPreview({
            request: buildRequest({
                headers: [
                    { key: "Host", value: "override.example.net" },
                    { key: "Content-Type", value: "application/custom" },
                    { key: "Cookie", value: "session=abc" },
                ],
            }),
        });

        expect(rowValue(rows, "Host")).toBe("override.example.net");
        expect(rowValue(rows, "Content-Type")).toBe("application/custom");
        expect(rowValue(rows, "Cookie")).toBe("session=abc");
    });

    it("calculates content length for raw/form/json bodies", () => {
        const rawRows = buildAutoGeneratedHeadersPreview({
            request: buildRequest({
                body: {
                    type: "raw",
                    content_type: "text/plain",
                    text: "hello",
                },
            }),
        });
        expect(rowValue(rawRows, "Content-Length")).toBe("5");
        expect(rowValue(rawRows, "Content-Type")).toBe("text/plain");

        const formRows = buildAutoGeneratedHeadersPreview({
            request: buildRequest({
                body: {
                    type: "form",
                    fields: [{ key: "a", value: "b c" }],
                },
            }),
        });
        expect(rowValue(formRows, "Content-Length")).toBe("5"); // "a=b+c"
        expect(rowValue(formRows, "Content-Type")).toBe("application/x-www-form-urlencoded");

        const jsonRows = buildAutoGeneratedHeadersPreview({
            request: buildRequest({
                body: {
                    type: "json",
                    value: { ok: true },
                },
            }),
        });
        expect(rowValue(jsonRows, "Content-Length")).toBe("11"); // {"ok":true}
        expect(rowValue(jsonRows, "Content-Type")).toBe("application/json");
    });

    it("keeps multipart content-length and content-type as calculated", () => {
        const rows = buildAutoGeneratedHeadersPreview({
            request: buildRequest({
                body: {
                    type: "multipart",
                    fields: [],
                },
            }),
        });

        expect(rowValue(rows, "Content-Length")).toBe(CALCULATED_HEADER_VALUE);
        expect(rowValue(rows, "Content-Type")).toBe(CALCULATED_HEADER_VALUE);
    });
});
