import type { KeyValue, Request } from "../types.ts";

const VARIABLE_PATTERN = /{{\s*([^{}]+?)\s*}}/g;

export const CALCULATED_HEADER_VALUE = "<calculated when request is sent>";
export const NOT_SET_HEADER_VALUE = "<not set>";

export type AutoGeneratedHeaderPreviewRow = {
    key: string;
    value: string;
    source: "auto" | "user";
    note: string;
};

type BuildAutoGeneratedHeadersPreviewArgs = {
    request: Request;
    variableValues?: Map<string, string>;
};

function lastHeaderValuesByName(headers: KeyValue[]): Map<string, string> {
    const map = new Map<string, string>();
    for (const header of headers) {
        const key = header.key.trim().toLowerCase();
        if (!key) continue;
        map.set(key, header.value);
    }
    return map;
}

function resolveKnownVariables(input: string, variableValues: Map<string, string>): {
    value: string;
    unresolved: boolean;
} {
    let unresolved = false;
    const value = input.replace(VARIABLE_PATTERN, (rawMatch, rawName: string) => {
        const name = rawName.trim();
        if (!name) return rawMatch;
        const resolved = variableValues.get(name);
        if (resolved === undefined) {
            unresolved = true;
            return rawMatch;
        }
        return resolved;
    });

    return { value, unresolved };
}

function utf8ByteLength(value: string): number {
    return new TextEncoder().encode(value).length;
}

function stripJsonComments(input: string): string {
    let out = "";
    let inString = false;
    let escaped = false;
    let inLineComment = false;
    let inBlockComment = false;

    for (let i = 0; i < input.length; i += 1) {
        const ch = input[i];
        const next = input[i + 1] ?? "";

        if (inLineComment) {
            if (ch === "\n") {
                inLineComment = false;
                out += ch;
            }
            continue;
        }

        if (inBlockComment) {
            if (ch === "*" && next === "/") {
                inBlockComment = false;
                i += 1;
                continue;
            }
            if (ch === "\n") {
                out += ch;
            }
            continue;
        }

        if (inString) {
            out += ch;
            if (escaped) {
                escaped = false;
                continue;
            }
            if (ch === "\\") {
                escaped = true;
                continue;
            }
            if (ch === "\"") {
                inString = false;
            }
            continue;
        }

        if (ch === "\"") {
            inString = true;
            out += ch;
            continue;
        }

        if (ch === "/" && next === "/") {
            inLineComment = true;
            i += 1;
            continue;
        }

        if (ch === "/" && next === "*") {
            inBlockComment = true;
            i += 1;
            continue;
        }

        out += ch;
    }

    return out;
}

function inferHost(url: string, variableValues: Map<string, string>): string {
    const resolved = resolveKnownVariables(url, variableValues);
    if (resolved.unresolved) {
        return CALCULATED_HEADER_VALUE;
    }

    try {
        const parsed = new URL(resolved.value);
        return parsed.host || CALCULATED_HEADER_VALUE;
    } catch {
        return CALCULATED_HEADER_VALUE;
    }
}

function inferContentLength(request: Request): string {
    const { body } = request;
    if (body.type === "raw") {
        return String(utf8ByteLength(body.text));
    }

    if (body.type === "json") {
        if (body.text && body.text.trim().length > 0) {
            return String(utf8ByteLength(stripJsonComments(body.text)));
        }
        try {
            const serialized = JSON.stringify(body.value);
            if (typeof serialized !== "string") {
                return CALCULATED_HEADER_VALUE;
            }
            return String(utf8ByteLength(serialized));
        } catch {
            return CALCULATED_HEADER_VALUE;
        }
    }

    if (body.type === "form") {
        const search = new URLSearchParams();
        for (const field of body.fields) {
            const key = field.key.trim();
            if (!key) continue;
            search.append(key, field.value);
        }
        return String(utf8ByteLength(search.toString()));
    }

    if (body.type === "multipart") {
        return CALCULATED_HEADER_VALUE;
    }

    return CALCULATED_HEADER_VALUE;
}

function inferContentType(request: Request): string {
    const { body } = request;
    if (body.type === "raw") {
        const contentType = body.content_type.trim();
        return contentType || NOT_SET_HEADER_VALUE;
    }
    if (body.type === "json") {
        return "application/json";
    }
    if (body.type === "form") {
        return "application/x-www-form-urlencoded";
    }
    if (body.type === "multipart") {
        return CALCULATED_HEADER_VALUE;
    }
    return NOT_SET_HEADER_VALUE;
}

function fromUserOrAuto(
    key: string,
    userHeaders: Map<string, string>,
    inferred: string,
    autoNote: string
): AutoGeneratedHeaderPreviewRow {
    const userValue = userHeaders.get(key.toLowerCase());
    if (userValue !== undefined) {
        return {
            key,
            value: userValue.length > 0 ? userValue : "\"\"",
            source: "user",
            note: "User-defined value",
        };
    }
    return {
        key,
        value: inferred,
        source: "auto",
        note: autoNote,
    };
}

export function buildAutoGeneratedHeadersPreview({
    request,
    variableValues,
}: BuildAutoGeneratedHeadersPreviewArgs): AutoGeneratedHeaderPreviewRow[] {
    const resolvedVariableValues = variableValues ?? new Map<string, string>();
    const userHeaders = lastHeaderValuesByName(request.headers);

    return [
        fromUserOrAuto("Host", userHeaders, inferHost(request.url, resolvedVariableValues), "Derived from request URL"),
        fromUserOrAuto("Content-Length", userHeaders, inferContentLength(request), "Calculated from request body"),
        fromUserOrAuto("Content-Type", userHeaders, inferContentType(request), "Derived from selected body type"),
        fromUserOrAuto("User-Agent", userHeaders, NOT_SET_HEADER_VALUE, "Not set by default"),
        fromUserOrAuto("Accept", userHeaders, "*/*", "reqwest default"),
        fromUserOrAuto("Accept-Encoding", userHeaders, CALCULATED_HEADER_VALUE, "Managed by HTTP client"),
        fromUserOrAuto("Connection", userHeaders, CALCULATED_HEADER_VALUE, "Managed by HTTP client"),
        fromUserOrAuto("Cookie", userHeaders, NOT_SET_HEADER_VALUE, "No automatic cookie jar configured"),
    ];
}
