import { describe, expect, it } from "vitest";
import type { Request } from "../types.ts";
import { defaultGeneratedHeaderControls } from "./requestHeadersPreview.ts";
import {
    buildRequestDebugInfo,
    buildRequestDebugText,
} from "./requestDebug.ts";

function buildRequest(overrides: Partial<Request> = {}): Request {
    return {
        id: "req_1",
        name: "Request 1",
        method: "post",
        url: "https://api.example.com/v1/login",
        headers: [],
        generated_headers: defaultGeneratedHeaderControls(),
        query: [],
        body: { type: "none" },
        auth: { type: "none" },
        tls: {
            allow_invalid_certificates: false,
            ca_certificate_path: "",
            client_certificate_path: "",
        },
        extractors: [],
        scripts: { pre_request: "", post_response: "" },
        ...overrides,
    };
}

describe("buildRequestDebugInfo", () => {
    it("omits disabled custom headers from enabled list", () => {
        const info = buildRequestDebugInfo({
            request: buildRequest({
                headers: [
                    { key: "X-Trace-Id", value: "abc", enabled: true },
                    { key: "X-Legacy", value: "1", enabled: false },
                ],
            }),
        });

        expect(info.enabledHeaders.some((header) => header.key === "X-Trace-Id")).toBe(true);
        expect(info.enabledHeaders.some((header) => header.key === "X-Legacy")).toBe(false);
        expect(info.disabledHeaders).toContain("X-Legacy");
    });

    it("includes disabled generated headers in disabled list", () => {
        const info = buildRequestDebugInfo({
            request: buildRequest({
                generated_headers: [
                    { key: "host", enabled: false },
                    { key: "content-length", enabled: false },
                ],
            }),
        });

        expect(info.disabledHeaders).toContain("Host");
        expect(info.disabledHeaders).toContain("Content-Length");
        expect(info.enabledHeaders.some((header) => header.key === "Host")).toBe(false);
    });

    it("includes enabled generated headers in enabled list", () => {
        const info = buildRequestDebugInfo({
            request: buildRequest(),
        });

        expect(info.enabledHeaders.some((header) => header.key === "Host")).toBe(true);
        expect(info.enabledHeaders.some((header) => header.key === "Accept")).toBe(true);
    });

    it("describes content-type generation from body type", () => {
        const autoInfo = buildRequestDebugInfo({
            request: buildRequest({
                body: { type: "json", value: { ok: true } },
            }),
        });
        expect(autoInfo.contentTypeMode).toBe("auto-generated by Bifrost");

        const disabledInfo = buildRequestDebugInfo({
            request: buildRequest({
                body: { type: "json", value: { ok: true } },
                generated_headers: [{ key: "content-type", enabled: false }],
            }),
        });
        expect(disabledInfo.contentTypeMode).toBe("disabled");
    });

    it("keeps multipart content-type as client-generated", () => {
        const info = buildRequestDebugInfo({
            request: buildRequest({
                body: { type: "multipart", fields: [] },
            }),
        });

        expect(info.contentTypeMode).toContain("multipart boundary");
    });
});

describe("buildRequestDebugText", () => {
    it("formats debug text with enabled/disabled headers and transport", () => {
        const info = buildRequestDebugInfo({
            request: buildRequest({
                generated_headers: [{ key: "host", enabled: false }],
                headers: [{ key: "Content-Type", value: "application/json", enabled: true }],
                body: { type: "json", value: { hello: "world" } },
            }),
        });
        const text = buildRequestDebugText(info);

        expect(text).toContain("Bifrost request debug");
        expect(text).toContain("Method: POST");
        expect(text).toContain("Enabled headers:");
        expect(text).toContain("Content-Type: application/json");
        expect(text).toContain("Disabled headers:");
        expect(text).toContain("Host");
        expect(text).toContain("Transport:");
        expect(text).toContain("TLS validation: enabled");
    });
});
